# Data type definitions.

from dataclasses import dataclass
from datetime import datetime
from typing import Literal

StorageMode = Literal["managed", "library", "external"]
PAStatus = Literal["pending", "confirmed", "rejected"]


def make_chunk_id(doc_id: str, chunker_version: str, chunk_index: int) -> str:
    return f"{doc_id}:{chunker_version}:{chunk_index}"


@dataclass(slots=True)
class Document:
    doc_id: str    # uuid
    pdf_sha256: str
    storage_mode: StorageMode
    pdf_path: str
    ingested_at: datetime
    title: str | None = None
    authors: str | None = None
    year: int | None = None
    doi: str | None = None


@dataclass(slots=True)
class Chunk:
    """
    A single retrievable unit of text.

    This is the canonical representation used downstream for embedding,
    indexing, and retrieval.
    """
    # Note: chunker_version is part of the derived chunk_id. If chunk
    # boundaries can change, chunker_version must change so old PA/CL
    # references continue to resolve to the old chunks.

    # Core identity
    doc_id: str  # uuid
    chunker_version: str
    chunk_index: int   # unique id within a doc (and chunker ver) (0-based)

    # Content
    text: str
    text_sha256: str

    page_start: int | None = None
    page_end: int | None = None

    @property
    def chunk_id(self) -> str:
        return make_chunk_id(
            self.doc_id,
            self.chunker_version,
            self.chunk_index,
        )


@dataclass(slots=True)
class SearchHit:
    """
    A retrieved chunk that matched a query embedding.
    """
    doc_id: str
    chunker_version: str
    chunk_index: int

    score: float

    chunk_text: str

    @property
    def chunk_id(self) -> str:
        return make_chunk_id(
            self.doc_id,
            self.chunker_version,
            self.chunk_index,
        )

@dataclass(slots=True)
class ProximityAlert:
    """
    A candidate semantic link between two chunks.

    Proximity alerts are generated by kurrent when two chunks appear
    semantically close enough to merit user review. A PA is permanent: it
    remains in the database whether it is still pending, later confirmed, or
    rejected.

    If the user confirms the alert, a ConfirmedLink is created that points
    back to this PA. The PA therefore records the original machine-generated
    suggestion, while the CL records the user's durable decision.
    """
    pa_id: str
    doc_a_id: str   # uuid
    chunker_a_version: str
    chunk_a_index: int
    doc_b_id: str   # uuid
    chunker_b_version: str
    chunk_b_index: int
    score: float
    status: PAStatus
    explanation_text: str
    created_at: datetime
    decided_at: datetime | None = None

    @property
    def chunk_a_id(self) -> str:
        return make_chunk_id(
            self.doc_a_id,
            self.chunker_a_version,
            self.chunk_a_index,
        )

    @property
    def chunk_b_id(self) -> str:
        return make_chunk_id(
            self.doc_b_id,
            self.chunker_b_version,
            self.chunk_b_index,
        )


@dataclass(slots=True)
class ConfirmedLink:
    """
    A user-confirmed semantic relationship between two chunks.

    A confirmed link represents durable user judgment: the user has reviewed
    a ProximityAlert and decided that the proposed connection is meaningful.
    The CL points back to the PA rather than duplicating its chunk references,
    score, or explanation.

    Confirmed links are part of kurrent's core user-created knowledge state
    and should not be deleted merely because chunks are re-embedded,
    re-indexed, or newer proximity alerts are generated.
    """
    cl_id: str   # uuid
    pa_id: str   # uuid
    created_at: datetime
    relationship_type: str | None = None
